language: node_js

cache:
  directories:
    - ~/.npm

branches:
  only:
    - master

notifications:
  email:
    - rong.shen@gmail.com

node_js:
  - '10'
  - '8'

script:
  - npm run test:prod && npm run build

jobs:
  include:
    - stage: release
      name: "Semantic Release"
      script: npm run semantic-release
