language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
